name: Emilie
favicon: null
layout_spectrum: 0.7561
typography_spectrum: 0.42747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fff6'
    - '#131114'
    - '#f91c23'
    - '#7b6a4e'
    - '#b8b8b6'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.4774832772091031
  rhythmicContrast: 0.75
purpose: []
