name: Emilie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4870890942402184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fff6'
    - '#131114'
    - '#f91c23'
    - '#7b6a4e'
    - '#b8b8b6'
  brandStrength: 0.43061490170657635
  lightness: 0.5449325877707452
  saturation: 0.4774832772091031
  rhythmicContrast: 0.25
purpose: []
