name: Emilie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4870890942402184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070b0a'
    - '#96a0a9'
    - '#a8c6ce'
    - '#f2dfce'
    - '#2f2c23'
  brandStrength: 0.43061490170657635
  lightness: 0.5449325877707452
  saturation: 0.4774832772091031
  rhythmicContrast: 0.10793719231151044
purpose: []
